version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_telegram_bot_test
    restart: always
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: telegram
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: my@mail.com
      PGADMIN_DEFAULT_PASSWORD: db
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
